@baseUrl = http://localhost:3004/api
@accessToken =  eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiMmVjMmY4YTEtMzI4MC00MGJiLWE4OWEtNjY0M2UwMjZmZDdlIiwiaWF0IjoxNzQ0OTU1NzU1LCJleHAiOjE3NDQ5OTE3NTV9.kJi1D7dFFAFz0YIxQiuuzicyoH0YGwjRTyoLb_TQiJUiLghkZwa_3YC80hK82e1ugwKAifQ8-Qqi91Oum8wdOqChGgmFzci5ScDDwqKP8RT5P8UL3s_Jn60tyP9giO5eGR8c33nl0typsR6mLGQEIg-SjOvY7gQWWNwqx5efq6Lzp-xjvwUNc4Cac1UKNAI8iRRMQ-9iofj3FFyW4zepBX1nNk1E-RQHMKEGXM2LTOe5nRT7ZWNMd-9Hd5FXwT2jDxDanBEpZ2WuUv9qCgl1aOcz7f9j6eqwFXVQEO7XOiB_lFGDZ9qLulGx5mfneQdyb6wD2rUPkP9gqCFcZAXgKg9luJLp4PCWj7vZcqsCQDrG9_JTYzRO8S2UvkcWPoouOIt3wj6KDvSba_0ntAm4ThdLXMjPM31AmspPETZByvv8At2RFYMFEjxSPyXrBeDNnZWq1ValS3BAZEJenL2HxrLmDrQfS9bmMJi3xLcRF-TWPzIusj6vsMpqYbAOJabE

@refreshToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiMmVjMmY4YTEtMzI4MC00MGJiLWE4OWEtNjY0M2UwMjZmZDdlIiwicmVzZXRDb3VudCI6MCwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDQ5NTU3NTV9.cZFOsgIlL8A2JgVgj4XMI7A7Qrn_LGvtPFJfvzF1iXBOwU5xeGXzUTOe6r85o5YpW_gCWyUkfn8SPVO7E7DSXsMu-N9cwm2uWBnC_ydduut3prkUpsJDQMl_9uqIxGZCZFTUaFlTk_3hEXrxUicG17DRlnpVCgc1OJS89dkzj1Ohs5tEUrgiHD0W2UwxQjH-4fmXcN6tKyVVYHMlDbwGRaj2jfPa_9G4MGVjvRLUIW270KG7SgDu9XXw91D8jR2wSmRhOhBBfHhzKXBp0m2tP2Y22NYu6qWIUi9aKzS0n5tXMhz5amyO0sxvPFkcKWqc5We0WAlLPI9fW6IRJ09g6sfPFUNTdu6RiorMzoakUlF8h69ODfIJkJrYkj0-sRCufHF_9RJxGsFiIHaDKR0FmCGytUbRI9v4nhxipxgaPW_iLd8DfGgMWDQqXYcvB7UmscrQlM-qeyQ4ZBiNz4HmOXgF7deDDraWDLlf4wa67MFPT3d9EQI0X9P5fZX38toA


### Note on authentication:
# This API uses dual token authentication:
# 1. Access token sent in Authorization header
# 2. Refresh token sent in cookies (automatically managed in browsers)
# 
# For testing with REST Client:
# - After login, copy the accessToken from the response to @accessToken variable
# - The refreshToken will be automatically saved in cookies if testing in a browser
# - For manual testing, you can use the Cookie header as shown in examples





### Authentication Endpoints ###

### Register
POST {{baseUrl}}/register
Content-Type: application/json

{
  "username": "testuser666",
  "password": "Password123"
}

### Login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "Password123"
}






### Group Endpoints ###

### Create Group
POST {{baseUrl}}/group/create-group
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "groupName": "TestGroup",
  "groupType": "scrum"
}

### Get Groups
GET {{baseUrl}}/group/get-groups
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here

### Get Group by ID
GET {{baseUrl}}/group/get-group/f21220d5-b95c-456a-a5b5-654786c36f08
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here

### Add Member to Group
GET {{baseUrl}}/group/add-member?groupId=f21220d5-b95c-456a-a5b5-654786c36f08&username=testuser666
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here

### Remove Member from Group
GET {{baseUrl}}/group/remove-member?groupId=f21220d5-b95c-456a-a5b5-654786c36f08&userId=testuser11
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here

### Delete Group
GET {{baseUrl}}/group/delete-group/group_id_here
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here





### Feature Endpoints ###

### Add Feature
POST {{baseUrl}}/feature/add-feature
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "name": "TestFeature",
  "groupId": "f21220d5-b95c-456a-a5b5-654786c36f08"
}

### Delete Feature
GET {{baseUrl}}/feature/delete-feature?featureId=15146ee3-499b-4d13-bf0b-0f8b36ef1050&groupId=f21220d5-b95c-456a-a5b5-654786c36f08
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here





### Epic Endpoints ###

### Add Epic
POST {{baseUrl}}/epic/add-epic
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "name": "TestEpic11",
  "groupId": "f21220d5-b95c-456a-a5b5-654786c36f08",
  "featureId": "c2458388-2570-40fc-a644-56d0c92106f3"
}

### Delete Epic
GET {{baseUrl}}/epic/delete-epic?epicId=29437c7f-a52a-492d-9e02-e0911e426b76&groupId=f21220d5-b95c-456a-a5b5-654786c36f08
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here





### Story Endpoints ###

### Add Story
POST {{baseUrl}}/story/add-story
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "name": "TestStory111",
  "description": "This is a test story1",
  "epicId": "8547ff27-cd08-47da-a687-469ce24b26d1",
  "groupId": "f21220d5-b95c-456a-a5b5-654786c36f08"
}

### Delete Story
GET {{baseUrl}}/story/delete-story?storyId=e8f0e4b9-1bc2-44a5-9369-2a8bce0e6dbf&groupId=f21220d5-b95c-456a-a5b5-654786c36f08
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here






### Sprint Endpoints ###

### Add Sprint
POST {{baseUrl}}/sprint/add-sprint
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "groupId": "f21220d5-b95c-456a-a5b5-654786c36f08"
}

### Start Sprint
POST {{baseUrl}}/sprint/start-sprint
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "groupId": "f21220d5-b95c-456a-a5b5-654786c36f08",
  "sprintId": "f5c525a0-6ec6-4025-97d3-9d873ea362ab"
}

### Link Story to Sprint
POST {{baseUrl}}/sprint/link-story
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "sprintId": "f5c525a0-6ec6-4025-97d3-9d873ea362ab",
  "storyId": "93dd76a2-d6f6-4914-a4d5-959ae1faf0a6"
}

### Unlink Story from Sprint
POST {{baseUrl}}/sprint/unlink-story/?sprintId=f5c525a0-6ec6-4025-97d3-9d873ea362ab&storyId=93dd76a2-d6f6-4914-a4d5-959ae1faf0a6
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here


### Update Story Status in Sprint
POST {{baseUrl}}/sprint/story-status
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "sprintId": "f5c525a0-6ec6-4025-97d3-9d873ea362ab",
  "storyId": "93dd76a2-d6f6-4914-a4d5-959ae1faf0a6",
  "start": true,
  "end": true
}

### Delete Sprint
GET {{baseUrl}}/sprint/delete-sprint?sprintId=f5c525a0-6ec6-4025-97d3-9d873ea362ab&groupId=f21220d5-b95c-456a-a5b5-654786c36f08
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here





### Chat Endpoints ###

### Send Group Message :type "message" : group , story, sprint
POST {{baseUrl}}/chat/add-message/group
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "message": "This is a test group message",
  "groupId": "f21220d5-b95c-456a-a5b5-654786c36f08"
}

### Send Story Message
POST {{baseUrl}}/chat/add-message/story
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "message": "This is a test story message",
  "groupId": "f21220d5-b95c-456a-a5b5-654786c36f08",
  "storyId": "93dd76a2-d6f6-4914-a4d5-959ae1faf0a6"
}

### Send Sprint Message
POST {{baseUrl}}/chat/add-message/sprint
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "message": "This is a test sprint message",
  "groupId": "f21220d5-b95c-456a-a5b5-654786c36f08",
  "sprintId": "ce9fd58f-0d28-4706-a770-736faf0dc4f6"
}

### Get Group Messages
GET {{baseUrl}}/chat/get-messages/group?groupId=f21220d5-b95c-456a-a5b5-654786c36f08
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here

### Get Story Messages
GET {{baseUrl}}/chat/get-messages/story?storyId=93dd76a2-d6f6-4914-a4d5-959ae1faf0a6&groupId=f21220d5-b95c-456a-a5b5-654786c36f08
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here

### Get Sprint Messages
GET {{baseUrl}}/chat/get-messages/sprint?sprintId=ce9fd58f-0d28-4706-a770-736faf0dc4f6&groupId=f21220d5-b95c-456a-a5b5-654786c36f08
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here
