@baseUrl = http://localhost:3002/api
@accessToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiZWRhZjU0YzQtNGU0Zi00NDY2LWJhODQtYjgwNDNjNzk0Y2Q2IiwiaWF0IjoxNzQ0OTUwNDYxLCJleHAiOjE3NDQ5ODY0NjF9.IEApOTOkGLjxRG7MVWDomYWj9MM1keeOg5vOivnwqS-0Zx_8Z44oEsYIV8gPZ2S_SikZMggKSueasMBPW9935r66-LkEF1g-S3zKpDKBPhYGbTmk3HDxgmlUbsCrkToRbeNFEH9gQgtbctiKLGtmn8Ju6YPgdvDWKtnNkRhzfL7QdnHcXGhiRKehHAJrB50uIS_bkU_fxGIMNpMJOe7ozcnUibumjuHwWRCgqW-QAz_bdnuzlkTo-Ns4QFtlFxxquWjJfk5oZKJHKBqcMSoCxRxWMX4dS3jfvY2dRrutsyLTS3DZ2mKqjTjXiO7kAJKNhFRl8fLVi8Q2IqhcsHm6BW5oSzpoiLo0rs2PbK1cJORdh5zUBr2Q1NMIMEdnBsU_TFeFA1w2B5Tc-r5ruD0GniVpsC03aHljo2MkaYV0JxWyltnYMmd8K3aHKgk3tC01-rKjvU4evcRQepW1cgtOOMw3PBxneYkqbtMxjAmROpF9KUobLj6CsleM7alnjEfK
@refreshToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiZWRhZjU0YzQtNGU0Zi00NDY2LWJhODQtYjgwNDNjNzk0Y2Q2IiwicmVzZXRDb3VudCI6MCwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDQ5NTA0NjF9.WOcxlj6KVGyD0uy24cFOWA1-VkzLFMYJo_ba1gOFZoM5W2uZZYxBx4cwiHsOZE2IyEJqTe9dE2MMCGENBAN-b-_qOdwbZz4X2N_2r6pLfn82KidqSTGMq9dWZkpdEHH3cIocMdo08BTUgBQQcGvDmv4HkF2r0-9lDLf6PFNS3cJiuuYn6yBHC6ONwJxvlRYEtKaNQxeGk5ceKWWMJL6BkfRzR9dZDiiFOw1_vhHxxKatqIaqBzuoxVUaGM5Nw-7dhX1rwTEUi3b8cM2FGafD3wJVdkaMZcGxETYD1tV3tO1KlrWcI0jZvCE1b9fnx4oUNwSMIyi--wgS-WyoYwoq7zlFG5_7g_MjPbndwmLnt6SahPdeXBFkL6KV-P7z0gVk0TgWTC3gEOJ6Z9al0ljJrdTVA4KMoCOK9VGMFNz_-mdnwQvyGqQB9-luxC9WQ2MS3NMap8PlaH3oXZpTwFDH2Ci-9lWNz8qvpbWHKb-D7uGg4c_YiJ7QkgB96uPSGUco

### Note on authentication:
# This API uses dual token authentication:
# 1. Access token sent in Authorization header
# 2. Refresh token sent in cookies (automatically managed in browsers)
# 
# For testing with REST Client:
# - After login, copy the accessToken from the response to @accessToken variable
# - The refreshToken will be automatically saved in cookies if testing in a browser
# - For manual testing, you can use the Cookie header as shown in examples

### Authentication Endpoints ###

### Register
POST {{baseUrl}}/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "Password123"
}

### Login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "Password123"
}

### Group Endpoints ###

### Create Group
POST {{baseUrl}}/group/create-group
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Cookie: refreshToken=your_refresh_token_here

{
  "groupName": "TestGroup",
  "groupType": "scrum"
}

### Get Groups
GET {{baseUrl}}/group/get-groups
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here

### Add Member to Group
GET {{baseUrl}}/group/add-member?groupId=group_id_here&username=username_here
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here

### Remove Member from Group
GET {{baseUrl}}/group/remove-member?groupId=group_id_here&userId=user_id_here
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here

### Delete Group
GET {{baseUrl}}/group/delete-group/group_id_here
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here

### Feature Endpoints ###

### Add Feature
POST {{baseUrl}}/feature/add-feature
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "name": "TestFeature",
  "groupId": "group_id_here"
}

### Delete Feature
GET {{baseUrl}}/feature/delete-feature?featureId=feature_id_here&groupId=group_id_here
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here

### Epic Endpoints ###

### Add Epic
POST {{baseUrl}}/epic/add-epic
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "name": "TestEpic",
  "groupId": "group_id_here",
  "featureId": "feature_id_here"
}

### Delete Epic
GET {{baseUrl}}/epic/delete-epic?epicId=epic_id_here&groupId=group_id_here
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here

### Story Endpoints ###

### Add Story
POST {{baseUrl}}/story/add-story
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "name": "TestStory",
  "description": "This is a test story",
  "groupId": "group_id_here",
  "epicId": "epic_id_here"
}

### Delete Story
GET {{baseUrl}}/story/delete-story?storyId=story_id_here&groupId=group_id_here
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here

### Sprint Endpoints ###

### Add Sprint
POST {{baseUrl}}/sprint/add-sprint
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "groupId": "group_id_here"
}

### Start Sprint
POST {{baseUrl}}/sprint/start-sprint
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "groupId": "group_id_here",
  "sprintId": "sprint_id_here"
}

### Link Story to Sprint
POST {{baseUrl}}/sprint/link-story
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "sprintId": "sprint_id_here",
  "storyId": "story_id_here"
}

### Unlink Story from Sprint
POST {{baseUrl}}/sprint/unlink-story/unlink
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here
query: sprintId=sprint_id_here&storyId=story_id_here

### Update Story Status in Sprint
POST {{baseUrl}}/sprint/story-status
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "sprintId": "sprint_id_here",
  "storyId": "story_id_here",
  "start": true,
  "end": false
}

### Delete Sprint
GET {{baseUrl}}/sprint/delete-sprint?sprintId=sprint_id_here&groupId=group_id_here
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here

### Chat Endpoints ###

### Send Group Message
POST {{baseUrl}}/chat/add-message/group
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "message": "This is a test group message",
  "groupId": "group_id_here"
}

### Send Story Message
POST {{baseUrl}}/chat/add-message/story
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "message": "This is a test story message",
  "groupId": "group_id_here",
  "storyId": "story_id_here"
}

### Send Sprint Message
POST {{baseUrl}}/chat/add-message/sprint
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "message": "This is a test sprint message",
  "groupId": "group_id_here",
  "sprintId": "sprint_id_here"
}

### Get Group Messages
GET {{baseUrl}}/chat/get-messages/group?groupId=group_id_here
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here

### Get Story Messages
GET {{baseUrl}}/chat/get-messages/story?storyId=story_id_here
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here

### Get Sprint Messages
GET {{baseUrl}}/chat/get-messages/sprint?sprintId=sprint_id_here
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here
