@baseUrl = http://localhost:3004/api
@accessToken =  eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiMmVjMmY4YTEtMzI4MC00MGJiLWE4OWEtNjY0M2UwMjZmZDdlIiwiaWF0IjoxNzQ1MDAxODI4LCJleHAiOjE3NDUwMzc4Mjh9.KhnJ1v145FmeBSRgXtGlKxR8MpU61IVyqTZAboSonFwVnUHU82GbqiYzPdG5HAgRmCOqXk2tRizwwhOaXCbgpk22jpEk4QjWEmDBXVZKre_B2VJd-PmWAG3RMjpLPRW5NB0kepG3-Ro8ZS-Z3VoU09O2B5__MXVbB-v2V4eTZ-MBydYaU3833yzETeo2pYXJOoBFN2mq8c2ev2-5eTJtcV3hz1Gt6bZhanjqHc_E0eaygQ5_307bd1UYyrKnXc8hbzNeevrzOaTSfk8m4K3u2ovvkyjGKvwE0U0AK4cxck5_nZiOjY46l5Kc-AHO1yDo9AUtXxiOnaBE0Iit1wiAXgniJoi0pkDS5qIL0vJBxSWLP7CO8g-XPaG_DGFaf8_R9BelYJhm_s9s40JMsPpEFaxiIO-8cISNWFsUHQCKhpbexRgmHwxbab1le_NtukvrW5G9mz8ecpnJjcJ3xNmFo1q7ngwZe9Xdl-PNK54HMhc71K4g3IbINIkdpaLY4QrW

@refreshToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiMmVjMmY4YTEtMzI4MC00MGJiLWE4OWEtNjY0M2UwMjZmZDdlIiwicmVzZXRDb3VudCI6MCwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDUwMDE4Mjh9.hvBUC6c-6FMDMu86EaM1sxElbtk1EQmDYvJexHRY7lVeWf3xjiNTMDChvq3_SAKBBlhrGVvmTcwitEnnEdJFLAIeWH6ovxqHArhA-Gnr8ndXespG1HHY6_640cTbETGt4rKwmuVF5qEdDq_FN5In96Sn1-5JjMIGJ_ffoOSUk6MYZDEZHYdkft7GKlOP86wn2emrLm3G8x2kJrkTvUqXwKeeP_1mvAD3RGWn9gW0pGBnD-sLF-0e9w8MaEx9GsAERO3Il5dOpsf9NBgKXBuolHY_dvOVBIXPGB0twhyXXMn1koQ3_RRs-IOnITemoFdfGSHYhkojupTRPvxqkWIDpGE5Z6BBtnmA7oKKkemDahcKaR_qx9MjMCHCGFvrABUY9Dl_LuFu2jUUqdA0DOLjoqA29It_OYYiVXj8RiZWfd4VjRqK8EjnShKYoR_w3uGpTNwcjx3T8YGEnolhsFe6XIxMKS5WAZ1EdJ_wTkbOEL9YVZOEGU4luBsDHDldZjRE


### Note on authentication:
# This API uses dual token authentication:
# 1. Access token sent in Authorization header
# 2. Refresh token sent in cookies (automatically managed in browsers)
# 
# For testing with REST Client:
# - After login, copy the accessToken from the response to @accessToken variable
# - The refreshToken will be automatically saved in cookies if testing in a browser
# - For manual testing, you can use the Cookie header as shown in examples





### Authentication Endpoints ###

### Register v
POST {{baseUrl}}/register
Content-Type: application/json

{
  "username": "testusffedr666",
  "password": "Password123"
}

### Login v
POST {{baseUrl}}/login
Content-Type: application/json

{
  "username": "Roody",
  "password": "Roody123"
}






### Group Endpoints ###

### Create Group v
POST {{baseUrl}}/group/create-group
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "groupName": "TestGroup",
  "groupType": "scrum"
}

### Get Groups v
GET {{baseUrl}}/group/get-groups
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here

### Get Group by ID v
GET {{baseUrl}}/group/get-group/f21220d5-b95c-456a-a5b5-654786c36f08
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here

### Add Member to Group
GET {{baseUrl}}/group/add-member?groupId=f21220d5-b95c-456a-a5b5-654786c36f08&username=testuser666
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here

### Remove Member from Group
GET {{baseUrl}}/group/remove-member?groupId=f21220d5-b95c-456a-a5b5-654786c36f08&userId=testuser11
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here

### Delete Group
GET {{baseUrl}}/group/delete-group/group_id_here
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here





### Feature Endpoints ###

### Add Feature
POST {{baseUrl}}/feature/add-feature
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "name": "TestFeature",
  "groupId": "f21220d5-b95c-456a-a5b5-654786c36f08"
}

### Delete Feature
GET {{baseUrl}}/feature/delete-feature?featureId=15146ee3-499b-4d13-bf0b-0f8b36ef1050&groupId=f21220d5-b95c-456a-a5b5-654786c36f08
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here





### Epic Endpoints ###

### Add Epic
POST {{baseUrl}}/epic/add-epic
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "name": "TestEpic11",
  "groupId": "f21220d5-b95c-456a-a5b5-654786c36f08",
  "featureId": "c2458388-2570-40fc-a644-56d0c92106f3"
}

### Delete Epic
GET {{baseUrl}}/epic/delete-epic?epicId=29437c7f-a52a-492d-9e02-e0911e426b76&groupId=f21220d5-b95c-456a-a5b5-654786c36f08
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here





### Story Endpoints ###

### Add Story
POST {{baseUrl}}/story/add-story
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "name": "TestStory111",
  "description": "This is a test story1",
  "epicId": "8547ff27-cd08-47da-a687-469ce24b26d1",
  "groupId": "f21220d5-b95c-456a-a5b5-654786c36f08"
}

### Delete Story
GET {{baseUrl}}/story/delete-story?storyId=e8f0e4b9-1bc2-44a5-9369-2a8bce0e6dbf&groupId=f21220d5-b95c-456a-a5b5-654786c36f08
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here






### Sprint Endpoints ###

### Add Sprint
POST {{baseUrl}}/sprint/add-sprint
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "groupId": "c3a7f1dc-ffff-4c0f-9814-bf83e85f66da"
}

### Start Sprint
POST {{baseUrl}}/sprint/start-sprint
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "groupId": "fc3a7f1dc-ffff-4c0f-9814-bf83e85f66da",
  "sprintId": "f5c525a0-6ec6-4025-97d3-9d873ea362ab"
}

### Link Story to Sprint
POST {{baseUrl}}/sprint/link-story
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "sprintId": "f5c525a0-6ec6-4025-97d3-9d873ea362ab",
  "storyId": "93dd76a2-d6f6-4914-a4d5-959ae1faf0a6"
}

### Unlink Story from Sprint
POST {{baseUrl}}/sprint/unlink-story/?sprintId=f5c525a0-6ec6-4025-97d3-9d873ea362ab&storyId=93dd76a2-d6f6-4914-a4d5-959ae1faf0a6
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here


### Update Story Status in Sprint
POST {{baseUrl}}/sprint/story-status
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "sprintId": "f5c525a0-6ec6-4025-97d3-9d873ea362ab",
  "storyId": "93dd76a2-d6f6-4914-a4d5-959ae1faf0a6",
  "start": true,
  "end": true
}

### Delete Sprint
GET {{baseUrl}}/sprint/delete-sprint?sprintId=f5c525a0-6ec6-4025-97d3-9d873ea362ab&groupId=f21220d5-b95c-456a-a5b5-654786c36f08
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here





### Chat Endpoints ###

### Send Group Message :type "message" : group , story, sprint
POST {{baseUrl}}/chat/add-message/group
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "message": "This is a test group message",
  "groupId": "f21220d5-b95c-456a-a5b5-654786c36f08"
}

### Send Story Message
POST {{baseUrl}}/chat/add-message/story
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "message": "This is a test story message",
  "groupId": "f21220d5-b95c-456a-a5b5-654786c36f08",
  "storyId": "93dd76a2-d6f6-4914-a4d5-959ae1faf0a6"
}

### Send Sprint Message
POST {{baseUrl}}/chat/add-message/sprint
Authorization: Bearer {{accessToken}}
Content-Type: application/json
# Cookie: refreshToken=your_refresh_token_here

{
  "message": "This is a test sprint message",
  "groupId": "f21220d5-b95c-456a-a5b5-654786c36f08",
  "sprintId": "ce9fd58f-0d28-4706-a770-736faf0dc4f6"
}

### Get Group Messages
GET {{baseUrl}}/chat/get-messages/group?groupId=f21220d5-b95c-456a-a5b5-654786c36f08
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here

### Get Story Messages
GET {{baseUrl}}/chat/get-messages/story?storyId=93dd76a2-d6f6-4914-a4d5-959ae1faf0a6&groupId=f21220d5-b95c-456a-a5b5-654786c36f08
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here

### Get Sprint Messages
GET {{baseUrl}}/chat/get-messages/sprint?sprintId=ce9fd58f-0d28-4706-a770-736faf0dc4f6&groupId=f21220d5-b95c-456a-a5b5-654786c36f08
Authorization: Bearer {{accessToken}}
# Cookie: refreshToken=your_refresh_token_here
